# Site settings
title: Marjan Stoimchev
email: marjanstoimcev@gmail.com
description: >-
  PhD Researcher in Machine Learning and Remote Sensing at Jožef Stefan Institute
baseurl: "" 
url: "https://marjanstoimchev.github.io"

# Social links
github_username: marjanstoimchev
linkedin_username: marjan-stoimchev-636657179
google_scholar_id: 05uc3wEAAAAJ

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "default"

# SEO and metadata
author:
  name: Marjan Stoimchev
  email: marjanstoimcev@gmail.com

# Timezone
timezone: Europe/Ljubljana

# Sass
sass:
  sass_dir: _sass
  style: compressed
