# Site configuration for GitHub Pages
title: "Marjan Stoimchev"
description: "PhD Researcher in Machine Learning & Computer Vision"
url: "https://yourusername.github.io"
baseurl: ""

# Personal information
author:
  name: "Marjan Stoimchev"
  email: "marjanstoimchev@gmail.com"
  location: "Ljubljana, Slovenia"
  linkedin: "https://www.linkedin.com/in/marjan-stoimchev-636657179/"
  scholar: "https://scholar.google.com/citations?user=05uc3wEAAAAJ&hl=en"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO settings
google_site_verification: # Add your verification code here
twitter:
  username: # Add if you have Twitter

# Navigation
header_pages:
  - index.md
  - publications.md
  - projects.md
  - cv.md

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Marjan Stoimchev"
