# Site settings
title: Marjan Stoimchev
email: marjanstoimcev@gmail.com
description: >-
  PhD Researcher in Machine Learning and Remote Sensing at Jožef Stefan Institute
baseurl: "" 
url: "https://marjanstoimchev.github.io"
twitter_username: 
github_username: marjanstoimchev
linkedin_username: marjan-stoimchev-636657179
google_scholar_id: 05uc3wEAAAAJ

# Build settings
markdown: kramdown
theme: minima # or custom
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:name/
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
